### PR TITLE
Implemented Swish

### PR DESCRIPTION
**Pull request by olegisk**

### CODE REVIEW

**Comment by olegisk** [comment]
@asbjornu No, it's part of WooCommerce payment plugin :-)

**Comment by asbjornu** [comment]
@olegisk, some of the code deals with low-level communication with PayEx' eCommerce Swish REST API and that's generic Swish communication code that in my opinion should reside within the PHP library. I'm thinking about code such as this:

https://github.com/PayEx/PayEx.Psp.WooCommerce/blob/0b00ac5b4c13401a9a1cf4265e28db00d87cef60/includes/class-wc-gateway-payex-swish.php#L251-L296

**Comment by olegisk** [comment]
@asbjornu I understand you. You are right, we have these lines in WooCommerce plugin now because plugin was implemented before PayEx.Ecommerce.Php. But we can make code refactoring.

**Comment by asbjornu** [comment]
@olegisk: When will you make the refactoring?

**Pull request merged**
